### ISSUE TITLE
Any plan to add typescript？

### ISSUE THREAD

**Issue by uglyspoon** [sanyuan0704/react-cloud-music#15]
有打算加入typescript吗，如果有计划很乐意提一个ts版本的pr

**Comment by sanyuan0704** [comment]
欢迎来提啊！很乐意加入新的活力




------------------ 原始邮件 ------------------
发件人: "uglyspoon"<notifications@github.com>; 
发送时间: 2019年8月30日(星期五) 下午5:38
收件人: "sanyuan0704/react-cloud-music"<react-cloud-music@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [sanyuan0704/react-cloud-music] Any plan to add typescript？ (#15)




有打算加入typescript吗，如果有计划很乐意提一个ts版本的pr
 
&mdash;

**Comment by sanyuan0704** [comment]
很抱歉，今天上午才有空看你pr，很不错，已经合并了。谢谢大佬的支持

**Comment by uglyspoon** [comment]
> 很抱歉，今天上午才有空看你pr，很不错，已经合并了。谢谢大佬的支持

客气啦，搬砖工而已哈哈，周末只顾着玩游戏了，工作日继续划水，持续关注这个项目 ；）
