### ISSUE TITLE
redux-thunk能换成redux-saga或redux-observable吗？

### ISSUE THREAD

**Issue by zwl1619** [sanyuan0704/react-cloud-music#22]
在掘金看到楼主的文章，很喜欢这个项目，我也喜欢用最新的写法。
同时，在掘金看到一篇redux异步中间件对比的文章，比较了redux-thunk、redux-saga、redux-observable三者的优劣：https://juejin.im/post/5d5f44dae51d4561df7805b4
![react001](https://user-images.githubusercontent.com/13177997/64350238-ed4d9800-d02a-11e9-8cd9-18627b3a4633.png)

redux-thunk给人弱爆了的感觉，所以，楼主能把redux-thunk换成redux-saga或redux-observable吗？

**Comment by sanyuan0704** [comment]
弱爆了？？？没打算换，你来提个pr如何
