### ISSUE TITLE
付费歌曲不能播放但是页面下边点进去歌词是会滚动的

### ISSUE THREAD

**Issue by liuguangsen0409** [sanyuan0704/react-cloud-music#31]
付费歌曲不能播放但是页面下边点进去歌词是会滚动的

如题 这个是 bug 吗
会提示 播放出错

**Comment by sanyuan0704** [comment]
额好吧，我改改让它切歌


---原始邮件---
发件人: &quot;liuguangsen0409&quot;<notifications@github.com&gt;
发送时间: 2019年10月15日(星期二) 下午4:41
收件人: &quot;sanyuan0704/react-cloud-music&quot;<react-cloud-music@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [sanyuan0704/react-cloud-music] 付费歌曲不能播放但是页面下边点进去歌词是会滚动的 (#31)



付费歌曲不能播放但是页面下边点进去歌词是会滚动的
 
如题 这个是 bug 吗
 会提示 播放出错
 
&mdash;

**Comment by liuguangsen0409** [comment]
秒回啊 老哥可以加个联系方式吗

**Comment by sanyuan0704** [comment]
github昵称就是我微信号


---原始邮件---
发件人: &quot;liuguangsen0409&quot;<notifications@github.com&gt;
发送时间: 2019年10月15日(星期二) 下午4:43
收件人: &quot;sanyuan0704/react-cloud-music&quot;<react-cloud-music@noreply.github.com&gt;;
抄送: &quot;sanyuan0704&quot;<494130947@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题: Re: [sanyuan0704/react-cloud-music] 付费歌曲不能播放但是页面下边点进去歌词是会滚动的 (#31)



秒回啊 老哥可以加个联系方式吗
 
&mdash;
