### ISSUE TITLE
这里直接调用了actionCreators方法可行吗？

### ISSUE THREAD

**Issue by codingJia** [sanyuan0704/react-cloud-music#34]
![image](https://user-images.githubusercontent.com/22971213/67171600-7279ea00-f3ea-11e9-9c61-2dff48834dd7.png)

这里直接调用了actionCreators方法可行吗？

**Comment by sanyuan0704** [comment]
不可行，因为你没有dispatch，这些action最终是要传入dispatch函数才有效的

**Comment by codingJia** [comment]
嗯嗯，是的，这个是你的源代码，我下载下来看到的，所以你这个player组件需要修改一下。你看下

**Comment by sanyuan0704** [comment]
------------------&nbsp;原始邮件&nbsp;-----------------
发件人:&nbsp;"Mr.chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月21日(星期一) 晚上9:12
收件人:&nbsp;"sanyuan0704/react-cloud-music"<react-cloud-music@noreply.github.com&gt;;
抄送:&nbsp;"杨兴元"<494130947@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [sanyuan0704/react-cloud-music] 这里直接调用了actionCreators方法可行吗？ (#34)




嗯嗯，是的，这个是你的源代码，我下载下来看到的，所以你这个player组件需要修改一下。你看下
 
—
收到！
