### ISSUE TITLE
第三章缺少依赖

### ISSUE THREAD

**Issue by bihongbin3027** [sanyuan0704/react-cloud-music#37]
scroll/index.js里面使用了prop-types，但是实际package.json里面没有add。

**Comment by sanyuan0704** [comment]
好的，谢谢反馈

**Comment by bihongbin3027** [comment]
在线地址访问不了了 @sanyuan0704

**Comment by sanyuan0704** [comment]
稍安勿躁，现在已经完稿了，某些原因不能放出来，过一段时间会和大家见面。

---原始邮件---
发件人: "bihongbin3027"<notifications@github.com&gt;
发送时间: 2019年10月31日(星期四) 中午11:17
收件人: "sanyuan0704/react-cloud-music"<react-cloud-music@noreply.github.com&gt;;
抄送: "sanyuan0704"<494130947@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [sanyuan0704/react-cloud-music] 第三章缺少依赖 (#37)



在线地址访问不了了 @sanyuan0704
