### ISSUE TITLE
电子书怎么关了

### ISSUE THREAD

**Issue by Genp0** [sanyuan0704/react-cloud-music#40]
还会开放阅读吗

**Comment by sanyuan0704** [comment]
月底掘金小册会上线的


---原始邮件---
发件人: &quot;Genp0&quot;<notifications@github.com&gt;
发送时间: 2019年11月22日(星期五) 下午4:45
收件人: &quot;sanyuan0704/react-cloud-music&quot;<react-cloud-music@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [sanyuan0704/react-cloud-music] 电子书怎么关了 (#40)



还会开放阅读吗
 
&mdash;
