### ISSUE TITLE
Player组件中的歌词问题

### ISSUE THREAD

**Issue by lichangchao15442** [sanyuan0704/react-cloud-music#48]
第一个问题：对歌词的解析。好像只解析了“02:10.158”这种格式的，像"02:10:158"这种格式的没有解析，所以有些原本有歌词的歌曲显示的是纯音乐；
第二个问题：歌词内容显示错乱（无意间发现的）：当前播放歌曲显示的歌词为纯音乐，点击下一首（有歌词的），然后再点击上一首（回到纯音乐），这时候本来是显示纯音乐却显示了刚刚那首歌的歌词；
第三个问题：CD和歌词组件切换，如果暂停歌曲，好像切换不了（或则反应很慢）；
第四个问题：搜索组件有一个小小的bug：点击清除按钮，input框的值没有清掉。

**Comment by sanyuan0704** [comment]
好的，谢谢指出！

**Comment by sanyuan0704** [comment]
你这四个问题已经全部解决。

**Comment by sanyuan0704** [comment]
1、lyric-parser.js解析正则做了修正
2、拿到歌词后如果无歌词，将currentLyric.current置为空
3.  这是useRef的问题，暂停状态下不会触发React组件的重新渲染，因此不适合采用useRef, 对于currentState变量用useState可以解决这个问题
4. 补充了相关的清空逻辑
